<?php
return [
    'admin'=>[
        1=>'sdasd',
        2=>'sdsds',
        3=>'qweqwe',
        4=>'asdasd',
        5=>'qweq',
        6=>'qweqw'
    ],
    'user'=>[
        1=>'sdasd',
        2=>'sdsds',
        3=>'qweqwe',
        4=>'asdasd',
        5=>'qweq',
        6=>'qweqw',
        7=>'asdasd',
        8=>'qweq',
        9=>'qweqw'
    ]
];
